
package tela;

import dao.MalandroDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import getterSetter.Malandro;

public class MalandroTela extends javax.swing.JFrame {
    MalandroDAO dao = new MalandroDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MalandroTela.class.getName());

    public MalandroTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEst = new javax.swing.JTextField();
        txtPen = new javax.swing.JTextField();
        txtJoi = new javax.swing.JTextField();
        btnReg = new javax.swing.JButton();
        btnAtu = new javax.swing.JButton();
        btnLis = new javax.swing.JButton();
        btnExc = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        btnMoto = new javax.swing.JButton();
        btnMulher = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Música: Estilo Cachorro - Racionais Mc's");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setText("Cadastro de malandro");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Estilo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Penteado:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Joias:");

        txtEst.addActionListener(this::txtEstActionPerformed);

        txtPen.addActionListener(this::txtPenActionPerformed);

        txtJoi.addActionListener(this::txtJoiActionPerformed);

        btnReg.setText("Registrar");
        btnReg.addActionListener(this::btnRegActionPerformed);

        btnAtu.setText("Atualizar");
        btnAtu.addActionListener(this::btnAtuActionPerformed);

        btnLis.setText("Listar");
        btnLis.addActionListener(this::btnLisActionPerformed);

        btnExc.setText("Excluir");
        btnExc.addActionListener(this::btnExcActionPerformed);

        btnLim.setText("Limpar");
        btnLim.addActionListener(this::btnLimActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("CPF:");

        txtCpf.addActionListener(this::txtCpfActionPerformed);

        btnMoto.setText("Moto");
        btnMoto.addActionListener(this::btnMotoActionPerformed);

        btnMulher.setText("Mulher");
        btnMulher.addActionListener(this::btnMulherActionPerformed);

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CPF", "Estilo", "Penteado", "Joias"
            }
        ));
        jScrollPane2.setViewportView(tabela1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txtEst, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtJoi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtPen, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReg)
                                .addGap(10, 10, 10)
                                .addComponent(btnLis)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtu)
                                .addGap(21, 21, 21)
                                .addComponent(btnExc))
                            .addComponent(btnLim))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMoto)
                        .addGap(18, 18, 18)
                        .addComponent(btnMulher))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtPen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtJoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReg)
                    .addComponent(btnLis)
                    .addComponent(btnAtu)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMoto)
                        .addComponent(btnMulher))
                    .addComponent(btnExc))
                .addGap(16, 16, 16)
                .addComponent(btnLim)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstActionPerformed

    private void txtPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenActionPerformed

    private void txtJoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJoiActionPerformed

    private void btnAtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtuActionPerformed
    Malandro m = new Malandro();
    m.setCpf(txtCpf.getText());
    m.setEstilo(txtEst.getText());
    m.setPenteado(txtPen.getText());
    m.setJoias(txtJoi.getText());

    dao.atualizar(m);
    btnLisActionPerformed(null); 
    
    }//GEN-LAST:event_btnAtuActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
                                               
    Malandro m = new Malandro();
    m.setCpf((txtCpf.getText()));
    m.setEstilo(txtEst.getText());
    m.setPenteado(txtPen.getText());
    m.setJoias(txtJoi.getText());

        try {
            dao.inserir(m);
        } catch (SQLException ex) {
            System.getLogger(MalandroTela.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        dao.listar(); // Atualiza a tabela
        


    

    }//GEN-LAST:event_btnRegActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed

     txtEst.setText("");
     txtPen.setText("");
     txtJoi.setText("");
             

    }//GEN-LAST:event_btnLimActionPerformed

    private void btnLisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLisActionPerformed
         DefaultTableModel modelo = (DefaultTableModel) tabela1.getModel();
    modelo.setRowCount(0);

    for (Malandro m : dao.listar()) {
        modelo.addRow(new Object[]{
            m.getCpf(),
            m.getEstilo(),
            m.getPenteado(),
            m.getJoias()
        });
    }
    }//GEN-LAST:event_btnLisActionPerformed

    private void btnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcActionPerformed
      int row = tabela1.getSelectedRow(); // Verificar se alguma linha foi selecionada
    
    if (row == -1) { // Nenhuma linha selecionada
        JOptionPane.showMessageDialog(this, "Selecione um registro para excluir!");
        return;
    }
    
    String cpf = tabela1.getValueAt(row, 0).toString(); // pega o CPF da linha

    int confirmacao = JOptionPane.showConfirmDialog(this, 
        "Tem certeza que deseja excluir o malandro com CPF: " + cpf + " ?", 
        "Confirmação", JOptionPane.YES_NO_OPTION);

    if (confirmacao == JOptionPane.YES_OPTION) {
        dao.deletar(cpf);  // chama o DAO para excluir
        btnLisActionPerformed(null); // atualiza a tabela
        JOptionPane.showMessageDialog(this, "Malandro excluido com sucesso!");
    }
    }//GEN-LAST:event_btnExcActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void btnMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoActionPerformed
         MotoTela motoTela = new MotoTela(); // abre a nova tela
         motoTela.setVisible(true);
    }//GEN-LAST:event_btnMotoActionPerformed

    private void btnMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulherActionPerformed
                                                 
      MulherTela mulherTela = new MulherTela();
      mulherTela.setVisible(true);

    }//GEN-LAST:event_btnMulherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MalandroTela().setVisible(true));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtu;
    private javax.swing.JButton btnExc;
    private javax.swing.JButton btnLim;
    private javax.swing.JButton btnLis;
    private javax.swing.JButton btnMoto;
    private javax.swing.JButton btnMulher;
    private javax.swing.JButton btnReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela1;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEst;
    private javax.swing.JTextField txtJoi;
    private javax.swing.JTextField txtPen;
    // End of variables declaration//GEN-END:variables

}

