
package tela;

import dao.MotoDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import getterSetter.Moto;

public class MotoTela extends javax.swing.JFrame {
    
        MotoDAO daoi = new MotoDAO();
//    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MotoTela.class.getName());

  
    public MotoTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnReg = new javax.swing.JButton();
        btnAtu = new javax.swing.JButton();
        btnLis = new javax.swing.JButton();
        btnExc = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        txtVin = new javax.swing.JTextField();
        txtMar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPes.addActionListener(this::txtPesActionPerformed);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "VIN", "Cor", "Marca", "Peso"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        btnReg.setText("Registrar");
        btnReg.addActionListener(this::btnRegActionPerformed);

        btnAtu.setText("Atualizar");
        btnAtu.addActionListener(this::btnAtuActionPerformed);

        btnLis.setText("Listar");
        btnLis.addActionListener(this::btnLisActionPerformed);

        btnExc.setText("Excluir");
        btnExc.addActionListener(this::btnExcActionPerformed);

        btnLim.setText("Limpar");
        btnLim.addActionListener(this::btnLimActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("VIN:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Música: Estilo Cachorro - Racionais Mc's");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setText("Cadastro de moto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cor:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Marca:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Peso:");

        txtCor.addActionListener(this::txtCorActionPerformed);

        txtVin.addActionListener(this::txtVinActionPerformed);

        txtMar.addActionListener(this::txtMarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReg)
                                .addGap(10, 10, 10)
                                .addComponent(btnLis)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtu)
                                .addGap(21, 21, 21)
                                .addComponent(btnExc))
                            .addComponent(btnLim)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(22, 22, 22)
                                    .addComponent(txtPes))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtMar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReg)
                            .addComponent(btnLis)
                            .addComponent(btnAtu)
                            .addComponent(btnExc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(btnLim)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed

        Moto mo = new Moto();
        mo.setVin(Integer.parseInt(txtVin.getText()));
        mo.setCor(txtCor.getText());
        mo.setMarca(txtMar.getText());
        mo.setPeso(Integer.parseInt(txtPes.getText()));

        try {
            daoi.inserir(mo);
        } catch (SQLException ex) {
            System.getLogger(MalandroTela.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        daoi.listar(); // Atualiza a tabela

    }//GEN-LAST:event_btnRegActionPerformed

    private void btnAtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtuActionPerformed
        Moto mo = new Moto();
        mo.setVin(Integer.parseInt(txtVin.getText()));
        mo.setCor(txtCor.getText());
        mo.setMarca(txtMar.getText());
        mo.setPeso(Integer.parseInt(txtPes.getText()));

        daoi.atualizar(mo);
        btnLisActionPerformed(null);

    }//GEN-LAST:event_btnAtuActionPerformed

    private void btnLisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLisActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setRowCount(0);

        for (Moto mo : daoi.listar()) {
            model.addRow(new Object[]{
                mo.getVin(),
                mo.getCor(),
                mo.getMarca(),
                mo.getPeso()
            });
        }
    }//GEN-LAST:event_btnLisActionPerformed

    private void btnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcActionPerformed
        int row = tabela.getSelectedRow(); // Verificar se alguma linha foi selecionada

        if (row == -1) { // Nenhuma linha selecionada
            JOptionPane.showMessageDialog(this, "Selecione um registro para excluir!");
            return;
        }

        int vin = Integer.parseInt(tabela.getValueAt(row, 0).toString()); 

        int confirmacao = JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja excluir a Moto com Vin: " + vin + " ?",
            "Confirmação", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            daoi.deletar(vin);  // chama o DAO para excluir
            btnLisActionPerformed(null); // atualiza a tabela
            JOptionPane.showMessageDialog(this, "Moto excluida com sucesso!");
        }
    }//GEN-LAST:event_btnExcActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed

        txtCor.setText("");
        txtMar.setText("");
        txtPes.setText("");

    }//GEN-LAST:event_btnLimActionPerformed

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVinActionPerformed

    private void txtMarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new MotoTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtu;
    private javax.swing.JButton btnExc;
    private javax.swing.JButton btnLim;
    private javax.swing.JButton btnLis;
    private javax.swing.JButton btnReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtMar;
    private javax.swing.JTextField txtPes;
    private javax.swing.JTextField txtVin;
    // End of variables declaration//GEN-END:variables
}
